{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"olist_customers_dataset\",\"olist_geolocation_dataset\",\"olist_order_items_dataset\",\"olist_order_payments_dataset\",\"olist_order_reviews_dataset\",\"olist_orders_dataset\",\"olist_products_dataset\",\"olist_sellers_dataset\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.1063.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "58b8fe55-fe2f-49dc-b160-2e257a5142fd",
        "fromColumn": "order_id",
        "fromTable": "olist_order_reviews_dataset",
        "toColumn": "order_id",
        "toTable": "olist_orders_dataset"
      },
      {
        "name": "bef50f91-705e-4bd2-9d8d-eb53750f6598",
        "fromColumn": "order_id",
        "fromTable": "olist_order_payments_dataset",
        "toColumn": "order_id",
        "toTable": "olist_orders_dataset"
      },
      {
        "name": "6cee8577-3660-4351-b4b6-b371411a4d24",
        "fromColumn": "order_id",
        "fromTable": "olist_order_items_dataset",
        "toColumn": "order_id",
        "toTable": "olist_orders_dataset"
      },
      {
        "name": "c5f7d541-0e15-4ea4-a9f7-34515ce7ad23",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "customer_id",
        "fromTable": "olist_customers_dataset",
        "toColumn": "order_id",
        "toTable": "olist_orders_dataset"
      },
      {
        "name": "f94321d1-2f0f-4b33-b271-256f899952c1",
        "fromColumn": "product_id",
        "fromTable": "olist_order_items_dataset",
        "toColumn": "product_id",
        "toTable": "olist_products_dataset"
      },
      {
        "name": "85d87a33-be07-4137-b699-abe6f68e5f8d",
        "fromColumn": "seller_id",
        "fromTable": "olist_order_items_dataset",
        "toColumn": "seller_id",
        "toTable": "olist_sellers_dataset"
      },
      {
        "name": "08242517-8c42-4082-adfe-7bd4519172a5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "geolocation_zip_code_prefix",
        "fromTable": "olist_geolocation_dataset",
        "toCardinality": "many",
        "toColumn": "seller_zip_code_prefix",
        "toTable": "olist_sellers_dataset"
      },
      {
        "name": "008ba255-be98-4cc1-b187-ee2512f015d7",
        "fromColumn": "shipping_limit_date",
        "fromTable": "olist_order_items_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_fc0c1bf0-532c-4e77-b184-7bdc250d5707"
      },
      {
        "name": "b86fee76-3767-4ef5-8651-ee84cfbb82c0",
        "fromColumn": "review_creation_date",
        "fromTable": "olist_order_reviews_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4caa530f-f339-4cb1-9a5c-f32caf3efd57"
      },
      {
        "name": "a53ec9d6-e97a-4d00-97ff-7b2298ddca05",
        "fromColumn": "review_answer_timestamp",
        "fromTable": "olist_order_reviews_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8626410c-5c36-47f3-b18a-e49e87aec523"
      },
      {
        "name": "94f96915-516d-4916-bdbd-984143dd02aa",
        "fromColumn": "order_purchase_timestamp",
        "fromTable": "olist_orders_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_341a4021-95aa-40fe-9ecf-8524625cb486"
      },
      {
        "name": "95102a9c-4b17-436d-935d-336580bd16ce",
        "fromColumn": "order_approved_at",
        "fromTable": "olist_orders_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7dae9154-549f-45b8-92ec-7151e17f8903"
      },
      {
        "name": "7aee0b60-fe60-49ae-8278-86e929a97595",
        "fromColumn": "order_delivered_carrier_date",
        "fromTable": "olist_orders_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ab6c0e8a-9c88-4c91-b86a-603c5316e422"
      },
      {
        "name": "9c76adf7-91df-44f8-81bc-6e4182a6b8c1",
        "fromColumn": "order_delivered_customer_date",
        "fromTable": "olist_orders_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1b5f4ef7-d613-4cc3-97c3-429533df853e"
      },
      {
        "name": "ef98af35-f84a-434b-a2dc-bb405f18b7d6",
        "fromColumn": "order_estimated_delivery_date",
        "fromTable": "olist_orders_dataset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0c08bee7-59ba-44b9-93b8-be8fbb98438c"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_abb017fa-5f54-4406-8d32-ffd71caa5842",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3be3132d-6593-4d67-a322-65bf8d4dd687",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b5587996-f1ad-49c8-82fc-b0fddd14022e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c870582b-871b-4515-944d-9c66b63e8d9f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8bdc895d-f9df-40cc-9231-4bab13489cce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "643cdeea-3fc5-4f1a-9902-3e533b6da13a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7ee56fe6-b6ea-40f8-80f5-75daa5ed355f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "03cb873f-dc3e-46fb-9ded-5f813879c4ea",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e49a4cf9-0010-4911-8834-8e0e577f8735",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d4979aab-0b97-4a61-b8c4-e00c87819a17",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "f99418e2-cd0f-4e7d-91ab-652703871a51",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "bb5bd407-a5ff-4161-9023-a41b7c467d42",
                "ordinal": 3
              }
            ],
            "lineageTag": "4a84b296-7b66-41b0-b84b-c9b30be46ce1"
          }
        ],
        "isPrivate": true,
        "lineageTag": "e44d575d-0e61-4000-8442-99d58da13401",
        "partitions": [
          {
            "name": "DateTableTemplate_abb017fa-5f54-4406-8d32-ffd71caa5842-3b4eba2e-f356-4c84-b204-7542508971ec",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0c08bee7-59ba-44b9-93b8-be8fbb98438c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e62b84c3-7568-455a-add2-412d2186ec24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b03c1250-958c-410f-a040-54dd3a2c87fe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "960938de-0718-4dae-9736-58e9e3b0a0c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9ab29fab-7a17-437b-8f53-5f89f7ca2e2f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "254f7a85-d5d2-4e1c-bf39-4baef3584003",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "dad2e748-ae37-40cb-a803-41a81d402545",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "1f1651c4-a54e-41ea-a39a-8023252e636d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e74cc372-7ac9-4d4f-bae2-94c8dafedf74",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c29cbad8-136a-4b5e-834e-1f49fcf58525",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "61781605-df8c-4d38-86a1-bcd6babaa9de",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "d4ffb6e7-9f82-424f-8d9c-8a05b8d5ac26",
                "ordinal": 3
              }
            ],
            "lineageTag": "74b2a44e-d5a8-4845-bd26-38a50a8b4fbe"
          }
        ],
        "lineageTag": "b6d037fa-96e3-4397-957c-07f80f32d678",
        "partitions": [
          {
            "name": "LocalDateTable_0c08bee7-59ba-44b9-93b8-be8fbb98438c-cc27e18b-fe86-4e9d-a947-49dfb5cd0eb7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_orders_dataset'[order_estimated_delivery_date])), 1, 1), Date(Year(MAX('olist_orders_dataset'[order_estimated_delivery_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1b5f4ef7-d613-4cc3-97c3-429533df853e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fca25a77-e6ca-4e27-8d33-d754e083bded",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "93c5fd6a-e794-4d7e-82a5-dcd2caee7f24",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e756f2da-b593-4b34-9d7d-ea27fce9e4b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "37bc0842-1e02-45b1-bea1-79f7cfe8e5a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "16ba197f-28d6-44ac-81e5-2528301c69e1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8bea14c8-681c-4051-9c7b-8f43b8bbad0e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "6ffcd804-185c-4e5e-8864-8bc9c8b88030",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "1b07b0e3-670a-4d42-9133-28a3983f288b",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4b03fa9c-9b2d-4ffd-879a-1914cb5c4885",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "2255562d-8d18-40a1-b44d-8635d622418b",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "d2901b9a-63a0-4435-8d23-bc7cd444653c",
                "ordinal": 3
              }
            ],
            "lineageTag": "272210bc-bec7-41d5-bfa2-3d6efbcd05b2"
          }
        ],
        "lineageTag": "6523eb8a-1189-49c2-8ba8-81dbff1eb89f",
        "partitions": [
          {
            "name": "LocalDateTable_1b5f4ef7-d613-4cc3-97c3-429533df853e-072f0a1c-ccd5-4df5-b9a9-daa5d361946b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_orders_dataset'[order_delivered_customer_date])), 1, 1), Date(Year(MAX('olist_orders_dataset'[order_delivered_customer_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_341a4021-95aa-40fe-9ecf-8524625cb486",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0ffab235-c928-4837-8765-0aa576bd4244",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f35cec3d-212b-4da5-bbc5-fb3d3c67a079",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2ded9ac7-c11c-474f-aaa6-4fb9b0012565",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0179f174-fe38-4aef-9173-b20844772f2c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "e699b8b9-6c0e-4b05-a23d-651f131d72f5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "df4c7cfb-3f7b-44e6-aced-7592e5f777cd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "26cf8a4f-37af-4a77-acfb-f1a0216125b8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "dac27df7-0664-4728-b876-32a70d53b5be",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3f18ac93-acf6-4ae8-bc00-0fb330ef8d3e",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "84faa83d-2fa3-4c1b-90dc-6e96e4aa5aa9",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "9a8dbe71-e7ff-4c1c-af7d-b5113a68e719",
                "ordinal": 3
              }
            ],
            "lineageTag": "a940341b-3ae0-4856-a9ab-73074cbb8e2d"
          }
        ],
        "lineageTag": "63b949d4-730c-4e95-868f-0f5754d52188",
        "partitions": [
          {
            "name": "LocalDateTable_341a4021-95aa-40fe-9ecf-8524625cb486-b541a05d-80f3-43ed-abc9-8e748aa92904",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_orders_dataset'[order_purchase_timestamp])), 1, 1), Date(Year(MAX('olist_orders_dataset'[order_purchase_timestamp])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4caa530f-f339-4cb1-9a5c-f32caf3efd57",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "45799bb1-76ef-4ec7-9196-fb9aa90bc9e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c16681c8-85a1-47e1-a13e-a9d384a20e3e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a1508ae2-ebcf-462c-9adf-6333aa6491fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a5f00af5-b54a-4752-a44c-564db9eea16f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "3b93292e-0dbb-410e-a4cd-0fee3c72265b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7b33789d-f49f-4a35-9b7a-a3bea837472c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "caf6d61d-b132-426e-98a4-9fced3cb514e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "2a105514-6681-4e46-888c-cd4b769c8358",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e2208d1d-82a5-4ca7-bee3-de4176efe40b",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b39d0820-1bb9-4e98-97db-bea62e275d20",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "3a4b17bd-6794-4c83-b520-778c4c5f1f0d",
                "ordinal": 3
              }
            ],
            "lineageTag": "34b6f0f7-75f3-43de-9697-3cad55a7c532"
          }
        ],
        "lineageTag": "c1ff0b67-c368-4d25-b7e5-4c21faf815be",
        "partitions": [
          {
            "name": "LocalDateTable_4caa530f-f339-4cb1-9a5c-f32caf3efd57-093a95f7-742d-4f98-ba82-6a6757c3a8b5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_order_reviews_dataset'[review_creation_date])), 1, 1), Date(Year(MAX('olist_order_reviews_dataset'[review_creation_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7dae9154-549f-45b8-92ec-7151e17f8903",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "edc42503-9b11-4f6f-a1d0-49e94f6b5c03",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fba95587-94cd-4e2f-a7ce-8c1e1a5322ec",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b6965139-4429-4acf-b528-b307f6ab93c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bfca820e-0531-4d47-bca6-95de192f11fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "36a5d346-d959-4f3c-b0e3-7d46c415db0a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c9c80ef7-f4a1-4a6e-9f31-bbf8602de363",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "05f9f02d-2658-474c-9aa9-394598a184d1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "c06e417c-ee6a-4331-9f6e-b1e6ea3fda08",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "464d5867-a9f3-49c3-9ae5-99a73bab6401",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "face7a6f-1d15-4896-b79c-e5a6965e126f",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "d90a30bd-b297-4292-b455-e3ecdddc1618",
                "ordinal": 3
              }
            ],
            "lineageTag": "a7b94c73-2c31-45c3-9a3f-77e6fb9fd33e"
          }
        ],
        "lineageTag": "ba31abee-ef17-4d58-8eb8-9cf9439feb10",
        "partitions": [
          {
            "name": "LocalDateTable_7dae9154-549f-45b8-92ec-7151e17f8903-7c9f1c72-2d7b-4733-ad81-f26ce80f9657",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_orders_dataset'[order_approved_at])), 1, 1), Date(Year(MAX('olist_orders_dataset'[order_approved_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8626410c-5c36-47f3-b18a-e49e87aec523",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "84361cbd-f04d-434d-86a0-d93af212eb91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8bf6c48f-69ee-459c-ac52-c735badf2c08",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b21932ed-e6c8-4b68-a744-3cebc3047504",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4a994512-edd6-47ce-83e5-0f31b3b6eb10",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "91b16547-7001-4521-a3a3-f7e0b9f6b5d6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4b25220a-1315-4893-ad5e-020da85a0089",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "20beaebb-d4c4-40ae-8257-0eb2748d1a7e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "c2cc0ec7-84ca-4c8b-85d0-afb6cc3e9eb8",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "2d9e8e74-2617-4677-9c10-b605f5e4862b",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "db048620-a181-4d67-bfe0-6b42da04cb01",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "5cd981a9-6ddc-4fb6-a87b-3591b86a30c0",
                "ordinal": 3
              }
            ],
            "lineageTag": "323cc85b-b79a-4f18-b9c2-1b3ed00a73f0"
          }
        ],
        "lineageTag": "4dbb121c-2adf-4487-8e96-f080698aab74",
        "partitions": [
          {
            "name": "LocalDateTable_8626410c-5c36-47f3-b18a-e49e87aec523-333e98e4-4868-41fd-9fc3-8fdf13bcb876",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_order_reviews_dataset'[review_answer_timestamp])), 1, 1), Date(Year(MAX('olist_order_reviews_dataset'[review_answer_timestamp])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ab6c0e8a-9c88-4c91-b86a-603c5316e422",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c94fc868-9588-403f-a4d4-39695db69cbe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "de5cecfb-90fd-491c-ada7-3b15dfee0b52",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ebbe0721-0b2d-4f59-8198-dbe02b0da1f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "5afeee4c-c8da-4989-9810-32cc672eb534",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "77a95d66-8b52-4292-b8cf-82a9f4f05d87",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6c523eff-c7fd-4452-8837-73db7ab7e5b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "c9edb404-8e49-4fd7-ae57-25b90ce840d8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "1e9f169c-4ca5-4b37-adf0-11c514822188",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "5faf05d4-b3fd-4461-b671-5aa800dfc1b0",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "af4180c8-9772-4ce4-9e29-421810e112c5",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "88bd2636-2b70-413d-a097-bb738e9ce883",
                "ordinal": 3
              }
            ],
            "lineageTag": "ae18f820-50c2-4d4d-8a4e-874ada4e579a"
          }
        ],
        "lineageTag": "d3dd12bb-dadc-4b27-9418-c044691f0605",
        "partitions": [
          {
            "name": "LocalDateTable_ab6c0e8a-9c88-4c91-b86a-603c5316e422-ab485e53-06fe-4c88-ba83-df16da699399",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_orders_dataset'[order_delivered_carrier_date])), 1, 1), Date(Year(MAX('olist_orders_dataset'[order_delivered_carrier_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_fc0c1bf0-532c-4e77-b184-7bdc250d5707",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6d67f17e-195e-4b62-b8e1-26db8d1b488a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8fee0ae9-f15f-4063-8083-fbc5937c5e7e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e2120af9-a6d7-4f41-bfe4-169faa26eb82",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "16d6f6e9-557e-4971-867e-69f2b5f6e025",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "5d31fd0c-6dfc-47e4-9860-9fa207110098",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "36db259a-62d7-4bd7-8ab9-7408158647b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "2cdbf36b-939a-4df7-8c02-7ded6bcf41de",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "2e693cd8-6055-4af7-b3e9-f166328202cc",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "f84590e0-0a08-4d94-8647-6c90f0697be7",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "c31958e2-db5a-40a6-8490-6c64c0f1fa2d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "6670ce8b-e514-46f5-aae7-0d03eb9e3b8b",
                "ordinal": 3
              }
            ],
            "lineageTag": "6f349809-0b18-4415-9502-4bb43b737e0a"
          }
        ],
        "lineageTag": "00579f64-a4ca-449d-89f4-87ab350486d7",
        "partitions": [
          {
            "name": "LocalDateTable_fc0c1bf0-532c-4e77-b184-7bdc250d5707-a004c918-5a07-432e-a6de-e9fed67d6bd3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('olist_order_items_dataset'[shipping_limit_date])), 1, 1), Date(Year(MAX('olist_order_items_dataset'[shipping_limit_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "_calcs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "29a0a8643ff84f60ac3776e9be523f05"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "eb6989d7-2644-440c-bb24-641ca172bf03",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f0610c7d-c53b-4e96-b669-73559da4f5d7",
        "measures": [
          {
            "name": "Total Sales Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "sum(olist_order_payments_dataset[payment_value])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "00d3ebba-0540-4090-855f-8567512f064d"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "COUNT(olist_order_payments_dataset[order_id])",
            "formatString": "0",
            "lineageTag": "7af716f9-9b75-4534-8d2b-448ec8c1c749"
          },
          {
            "name": "Avg. Ticket",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "divide([Total Sales Value], [Total Sales])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "f891f067-8f2b-4548-a6d2-6dc7351d55bd"
          },
          {
            "name": "Avg. Days to Delivery",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(olist_orders_dataset[Purchase to Delivered]),",
              "        olist_orders_dataset[order_status] = \"delivered\",",
              "        WEEKDAY(olist_orders_dataset[order_delivered_customer_date]) <> 1,",
              "        WEEKDAY(olist_orders_dataset[order_delivered_customer_date]) <> 7",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e31ad6ac-9d2a-423b-8786-3059d0109aab"
          },
          {
            "name": "Delays",
            "expression": "calculate(count(olist_orders_dataset[order_id]), olist_orders_dataset[Delivery] < 0 && olist_orders_dataset[order_status]=\"Delivered\")",
            "formatString": "0",
            "lineageTag": "ac1ab091-009b-4889-89a3-dcfafb3c7417"
          },
          {
            "name": "Delayed Deliveries",
            "expression": "divide([Delays], [Total Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c4fae486-d034-4545-9569-db7af1993c94"
          },
          {
            "name": "Total Canceled",
            "expression": [
              "",
              "CALCULATE(count(olist_orders_dataset[order_id]), olist_orders_dataset[order_status] = \"canceled\")"
            ],
            "formatString": "0",
            "lineageTag": "67323265-fe60-464c-abbf-427c92140ae1"
          },
          {
            "name": "Avg. Delayed Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(olist_orders_dataset[Purchase to Delivered]),",
              "        olist_orders_dataset[order_status] = \"delivered\",",
              "        olist_orders_dataset[Purchase to Delivered] < 0",
              ")"
            ],
            "lineageTag": "0904cc4f-2559-4ae4-bab3-a657981c1390"
          }
        ],
        "partitions": [
          {
            "name": "_calcs-c8084ca6-2dca-46fa-8776-92845d7b7e43",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "olist_customers_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "customer_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ff41735-6082-474f-af3a-fe8f9c834366",
            "sourceColumn": "customer_city",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ae1e921-c64c-45ca-b1ce-68f042aa70b8",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5415c5d8-caa0-4e70-97b5-eb97ae51bcf1",
            "sourceColumn": "customer_state",
            "summarizeBy": "none"
          },
          {
            "name": "customer_unique_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5efedc61-4f0c-483f-8d0f-5a9e95ab7866",
            "sourceColumn": "customer_unique_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_zip_code_prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "312f7878-70ea-4d33-94c4-5ac028a410bb",
            "sourceColumn": "customer_zip_code_prefix",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e37c62bc-0372-48c9-b541-c6e67a58df20",
        "partitions": [
          {
            "name": "olist_customers_dataset-a36de522-6066-4eb0-801b-5e6c4a03ebfa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_customers_dataset.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
                "in",
                "    #\"Cabeçalhos Promovidos\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_geolocation_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "geolocation_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4b73a4f-2abc-40f4-b833-118fab81d042",
            "sourceColumn": "geolocation_city",
            "summarizeBy": "none"
          },
          {
            "name": "geolocation_lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6faeeb47-6b16-413f-9472-02ec32c1baa8",
            "sourceColumn": "geolocation_lat",
            "summarizeBy": "none"
          },
          {
            "name": "geolocation_lng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb4ba7e2-e207-4c55-b1aa-fed032b9a1bd",
            "sourceColumn": "geolocation_lng",
            "summarizeBy": "none"
          },
          {
            "name": "geolocation_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d45aae7-635f-4043-94ce-b0021710b574",
            "sourceColumn": "geolocation_state",
            "summarizeBy": "none"
          },
          {
            "name": "geolocation_zip_code_prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cff5a89d-c23a-4315-b876-cfec29e75676",
            "sourceColumn": "geolocation_zip_code_prefix",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fdda6a01-2f5f-41f4-9886-bcf79b9f4fcf",
        "partitions": [
          {
            "name": "olist_geolocation_dataset-ad6a07bc-5b4e-4c81-8d70-8aac1d37a3dd",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_geolocation_dataset.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
                "in",
                "    #\"Cabeçalhos Promovidos\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_order_items_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "freight_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "12f4e447-50ad-4b2f-b836-ae9a2c4ca897",
            "sourceColumn": "freight_value",
            "summarizeBy": "sum"
          },
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd69847f-9fb6-45df-9602-422a0b417ac4",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e8272ec-a8b9-4441-8d17-7101b394fcbb",
            "sourceColumn": "order_item_id",
            "summarizeBy": "none"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "e70be9e7-7c34-4d67-a565-5c12979f1f69",
            "sourceColumn": "price",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd933c67-d1c0-4fcf-aa2f-6d58848834ba",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "seller_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5471f3c1-9a9a-410a-9080-b43eeafa449b",
            "sourceColumn": "seller_id",
            "summarizeBy": "none"
          },
          {
            "name": "shipping_limit_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ed0a2642-6313-4961-9f64-e404f39cb344",
            "sourceColumn": "shipping_limit_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_fc0c1bf0-532c-4e77-b184-7bdc250d5707"
                },
                "isDefault": true,
                "relationship": "008ba255-be98-4cc1-b187-ee2512f015d7"
              }
            ]
          }
        ],
        "lineageTag": "d66f83ec-d014-4695-9740-cb1057960431",
        "partitions": [
          {
            "name": "olist_order_items_dataset-9e830fa5-64fa-49de-b5a4-3bbe2d29c7f4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_order_items_dataset.csv\"),[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"shipping_limit_date\", type datetime}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\".\",\",\",Replacer.ReplaceText,{\"price\", \"freight_value\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"price\", Currency.Type}, {\"freight_value\", Currency.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_order_payments_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd74bc6d-a973-4325-ae47-658d2c894c04",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "payment_installments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f2b86a8-9e82-4942-b332-b7d745fd80da",
            "sourceColumn": "payment_installments",
            "summarizeBy": "sum"
          },
          {
            "name": "payment_sequential",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "803170d9-7c74-47f9-96af-280aa7c63d1c",
            "sourceColumn": "payment_sequential",
            "summarizeBy": "none"
          },
          {
            "name": "payment_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc3ccdeb-80d8-4568-ae00-fa06c974d676",
            "sourceColumn": "payment_type",
            "summarizeBy": "none"
          },
          {
            "name": "payment_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "e1dd3dae-e451-4f94-927c-2079bd2db5aa",
            "sourceColumn": "payment_value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a2035c67-8612-4425-b735-7c6100308d26",
        "partitions": [
          {
            "name": "olist_order_payments_dataset-13b7ad76-8881-4060-a626-e62ed8404002",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_order_payments_dataset.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"payment_installments\", Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\".\",\",\",Replacer.ReplaceText,{\"payment_value\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"payment_value\", Currency.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_order_reviews_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8929751b-38bf-46ff-bc2e-ba0fd68dbc01",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "review_answer_timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "654d1b3e-8198-481c-ba4e-cdfe21e0cfb9",
            "sourceColumn": "review_answer_timestamp",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_8626410c-5c36-47f3-b18a-e49e87aec523"
                },
                "isDefault": true,
                "relationship": "a53ec9d6-e97a-4d00-97ff-7b2298ddca05"
              }
            ]
          },
          {
            "name": "review_comment_message",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d95c84fb-042a-4c93-8c71-ef1c17620666",
            "sourceColumn": "review_comment_message",
            "summarizeBy": "none"
          },
          {
            "name": "review_comment_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2402f225-625f-46df-bd3e-a9c19b511b54",
            "sourceColumn": "review_comment_title",
            "summarizeBy": "none"
          },
          {
            "name": "review_creation_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "407f1162-24fc-4562-be3e-1c9f4a302639",
            "sourceColumn": "review_creation_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_4caa530f-f339-4cb1-9a5c-f32caf3efd57"
                },
                "isDefault": true,
                "relationship": "b86fee76-3767-4ef5-8651-ee84cfbb82c0"
              }
            ]
          },
          {
            "name": "review_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b83211d4-a6d5-48f8-9926-a3cd73c479f5",
            "sourceColumn": "review_id",
            "summarizeBy": "none"
          },
          {
            "name": "review_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d1a78ebc-641c-4ec4-ac19-4d3002b2c444",
            "sourceColumn": "review_score",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2e2e12c8-2442-46a6-9289-a51d8e042d17",
        "partitions": [
          {
            "name": "olist_order_reviews_dataset-85374184-35e9-4176-8b38-73265577aef4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_order_reviews_dataset.csv\"),[Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"review_creation_date\", type datetime}, {\"review_answer_timestamp\", type datetime}, {\"review_score\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_orders_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Delivery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "[order_estimated_delivery_date] - [order_delivered_customer_date]",
            "formatString": "0",
            "lineageTag": "01fcc525-1ae6-4c40-97d5-492cc2c08d50",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Purchase to Delivered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "olist_orders_dataset[order_delivered_customer_date] - olist_orders_dataset[order_approved_at]",
            "formatString": "0",
            "lineageTag": "4f14fc9f-8922-4df2-a49a-850b585efdbc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "WeekdayColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY(olist_orders_dataset[order_delivered_customer_date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9e3bc476-e7cb-424f-bfb0-5e81470b1e0e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "fec2eb65-5a6d-4773-bc0c-3dd4b61362d4",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_approved_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "fc7a144c-9e18-4b28-980d-dd2be0db28fa",
            "sourceColumn": "order_approved_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7dae9154-549f-45b8-92ec-7151e17f8903"
                },
                "isDefault": true,
                "relationship": "95102a9c-4b17-436d-935d-336580bd16ce"
              }
            ]
          },
          {
            "name": "order_delivered_carrier_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2b04f7ee-fd4e-46e7-b8fc-d3abfbd398b2",
            "sourceColumn": "order_delivered_carrier_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_ab6c0e8a-9c88-4c91-b86a-603c5316e422"
                },
                "isDefault": true,
                "relationship": "7aee0b60-fe60-49ae-8278-86e929a97595"
              }
            ]
          },
          {
            "name": "order_delivered_customer_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "01d2e1d6-9a12-4ee7-9df4-71e990add2e2",
            "sourceColumn": "order_delivered_customer_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_1b5f4ef7-d613-4cc3-97c3-429533df853e"
                },
                "isDefault": true,
                "relationship": "9c76adf7-91df-44f8-81bc-6e4182a6b8c1"
              }
            ]
          },
          {
            "name": "order_estimated_delivery_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f4c16a61-e8d7-4b08-8c92-f8f73829ddc7",
            "sourceColumn": "order_estimated_delivery_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_0c08bee7-59ba-44b9-93b8-be8fbb98438c"
                },
                "isDefault": true,
                "relationship": "ef98af35-f84a-434b-a2dc-bb405f18b7d6"
              }
            ]
          },
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cda16e6c-a476-4877-af26-7ff32becf945",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_purchase_timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "22dcf30d-16b0-4650-b6a9-eac8ab73111b",
            "sourceColumn": "order_purchase_timestamp",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_341a4021-95aa-40fe-9ecf-8524625cb486"
                },
                "isDefault": true,
                "relationship": "94f96915-516d-4916-bdbd-984143dd02aa"
              }
            ]
          },
          {
            "name": "order_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "68ba8f59-b10a-4777-a563-623b42fecebf",
            "sourceColumn": "order_status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5ee2fab4-46ea-47ae-b5bf-4a585538b6a0",
        "partitions": [
          {
            "name": "olist_orders_dataset-1e76de2c-cc6a-4193-a97a-e3e80765048d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_orders_dataset.csv\"),[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"order_purchase_timestamp\", type datetime}, {\"order_approved_at\", type datetime}, {\"order_delivered_carrier_date\", type datetime}, {\"order_delivered_customer_date\", type datetime}, {\"order_estimated_delivery_date\", type datetime}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_products_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "product_category_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "54e0a9bf-5ec1-4a6a-bea5-ea9eb662cf36",
            "sourceColumn": "product_category_name",
            "summarizeBy": "none"
          },
          {
            "name": "product_description_lenght",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2390219-a9c2-4b22-ae6d-2f79a766e648",
            "sourceColumn": "product_description_lenght",
            "summarizeBy": "none"
          },
          {
            "name": "product_height_cm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b08aba88-8e59-4935-a51f-121083f591c3",
            "sourceColumn": "product_height_cm",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bc0887c-062b-4133-8998-c4c9705c7728",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_length_cm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "45ef5a96-e237-418a-9df3-7527c13f032b",
            "sourceColumn": "product_length_cm",
            "summarizeBy": "none"
          },
          {
            "name": "product_name_lenght",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03dba441-7d0c-418a-bb7f-972813692085",
            "sourceColumn": "product_name_lenght",
            "summarizeBy": "none"
          },
          {
            "name": "product_photos_qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c27e702a-5e8a-4cc4-b981-91171d63aec7",
            "sourceColumn": "product_photos_qty",
            "summarizeBy": "none"
          },
          {
            "name": "product_weight_g",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "113425c9-b7c6-45f5-8576-ad6d6464a9b8",
            "sourceColumn": "product_weight_g",
            "summarizeBy": "none"
          },
          {
            "name": "product_width_cm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a3f6069-1fda-40be-86d9-f4fa3449459d",
            "sourceColumn": "product_width_cm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b2a04c0a-5996-4648-96c3-cac074713589",
        "partitions": [
          {
            "name": "olist_products_dataset-705b75a6-82d8-47f0-b884-f9c6f66ea991",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_products_dataset.csv\"),[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"product_name_lenght\", Int64.Type}, {\"product_description_lenght\", Int64.Type}, {\"product_photos_qty\", Int64.Type}, {\"product_weight_g\", Int64.Type}, {\"product_length_cm\", Int64.Type}, {\"product_height_cm\", Int64.Type}, {\"product_width_cm\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "olist_sellers_dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "seller_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "68a297ae-b6fe-4a90-af97-8e684907dd3b",
            "sourceColumn": "seller_city",
            "summarizeBy": "none"
          },
          {
            "name": "seller_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2690f39-59be-4659-aedb-36407268de0d",
            "sourceColumn": "seller_id",
            "summarizeBy": "none"
          },
          {
            "name": "seller_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c43f1632-dc21-4fb5-811d-a459e4c7f9dd",
            "sourceColumn": "seller_state",
            "summarizeBy": "none"
          },
          {
            "name": "seller_zip_code_prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "320c5e57-45af-40e0-8d51-78f789b8806d",
            "sourceColumn": "seller_zip_code_prefix",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "621c90ff-d4f9-43e0-b872-def04b8eab4f",
        "partitions": [
          {
            "name": "olist_sellers_dataset-9b858970-ebdc-432e-8745-cf2fccdc38e1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Work\\Desktop\\Studies\\GitHub\\olist\\data\\olist_sellers_dataset.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
                "in",
                "    #\"Cabeçalhos Promovidos\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}